// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi772Oz5EycNubeI1ca5GEKvZ7iLU5EEw',
    appId: '1:149191170997:web:9d95293d4f8fbf6366d7fc',
    messagingSenderId: '149191170997',
    projectId: 'smartpark-6fae3',
    authDomain: 'smartpark-6fae3.firebaseapp.com',
    storageBucket: 'smartpark-6fae3.appspot.com',
    measurementId: 'G-RSZ625SRBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NGTAYnoXInjDtaGfvhGbbJUg4jG9QvA',
    appId: '1:149191170997:android:1f1c116e5882354866d7fc',
    messagingSenderId: '149191170997',
    projectId: 'smartpark-6fae3',
    storageBucket: 'smartpark-6fae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBK59WoAGbynUeAewKl3zmXYjt8P0SbAA',
    appId: '1:149191170997:ios:420aa601aa7d684066d7fc',
    messagingSenderId: '149191170997',
    projectId: 'smartpark-6fae3',
    storageBucket: 'smartpark-6fae3.appspot.com',
    iosBundleId: 'com.example.smartpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBK59WoAGbynUeAewKl3zmXYjt8P0SbAA',
    appId: '1:149191170997:ios:420aa601aa7d684066d7fc',
    messagingSenderId: '149191170997',
    projectId: 'smartpark-6fae3',
    storageBucket: 'smartpark-6fae3.appspot.com',
    iosBundleId: 'com.example.smartpark',
  );
}
